<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CrossPlatformPatcher</AssemblyName>
    <RootNamespace>CrossPlatformPatcher</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dnlib" Version="4.4.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.17.3" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.17.3" GeneratePathProperty="true" />
    
    <PackageReference Include="System.Memory" Version="4.5.5" GeneratePathProperty="true" />
    <PackageReference Include="System.Buffers" Version="4.5.1" GeneratePathProperty="true" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" GeneratePathProperty="true" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.3" GeneratePathProperty="true" />
  </ItemGroup>

  <Target Name="BuildOWW" BeforeTargets="BeforeBuild">
    <Exec Command="dotnet build PAIcom.OWW/PAIcom.OWW.csproj -c Release" />
  </Target>
  <Target Name="AddOWWResource" BeforeTargets="PrepareForBuild" DependsOnTargets="BuildOWW">
    <ItemGroup>
      <EmbeddedResource Include="PAIcom.OWW\bin\Release\netstandard2.0\PAIcom.OWW.dll">
        <LogicalName>PAIcom.OWW.dll</LogicalName>
      </EmbeddedResource>
    </ItemGroup>
  </Target>

  <ItemGroup>
    <EmbeddedResource Include="$(PkgSystem_Memory)\lib\netstandard2.0\System.Memory.dll" LogicalName="System.Memory.dll" />
    <EmbeddedResource Include="$(PkgSystem_Buffers)\lib\netstandard2.0\System.Buffers.dll" LogicalName="System.Buffers.dll" />
    <EmbeddedResource Include="$(PkgSystem_Numerics_Vectors)\lib\netstandard2.0\System.Numerics.Vectors.dll" LogicalName="System.Numerics.Vectors.dll" />
    <EmbeddedResource Include="$(PkgSystem_Runtime_CompilerServices_Unsafe)\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll" LogicalName="System.Runtime.CompilerServices.Unsafe.dll" />
    <EmbeddedResource Include="$(PkgMicrosoft_ML_OnnxRuntime_Managed)\lib\netstandard2.0\Microsoft.ML.OnnxRuntime.dll" LogicalName="onnxruntime.managed.dll" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Core\NativeLibraries\vosk-win-x64.dll" LogicalName="vosk.native.win-x64.dll" Condition="Exists('Core\NativeLibraries\vosk-win-x64.dll')" />
    <EmbeddedResource Include="Core\NativeLibraries\vosk-win-gcc.dll" LogicalName="vosk.native.win-gcc.dll" Condition="Exists('Core\NativeLibraries\vosk-win-gcc.dll')" />
    <EmbeddedResource Include="Core\NativeLibraries\vosk-win-stdc.dll" LogicalName="vosk.native.win-stdc.dll" Condition="Exists('Core\NativeLibraries\vosk-win-stdc.dll')" />
    <EmbeddedResource Include="Core\NativeLibraries\vosk-win-pthread.dll" LogicalName="vosk.native.win-pthread.dll" Condition="Exists('Core\NativeLibraries\vosk-win-pthread.dll')" />
    <EmbeddedResource Include="Core\NativeLibraries\libvosk-linux-x64.so" LogicalName="vosk.native.linux-x64.so" Condition="Exists('Core\NativeLibraries\libvosk-linux-x64.so')" />
    <EmbeddedResource Include="Core\NativeLibraries\libvosk-linux-arm64.so" LogicalName="vosk.native.linux-arm64.so" Condition="Exists('Core\NativeLibraries\libvosk-linux-arm64.so')" />
    <EmbeddedResource Include="Core\NativeLibraries\libvosk-osx-universal.dylib" LogicalName="vosk.native.osx.dylib" Condition="Exists('Core\NativeLibraries\libvosk-osx-universal.dylib')" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Core\ManagedLibraries\Vosk.dll" LogicalName="vosk.managed.dll" Condition="Exists('Core\ManagedLibraries\Vosk.dll')" />
    <EmbeddedResource Include="Core\ManagedLibraries\NAudio.Core.dll" LogicalName="naudio.core.dll" Condition="Exists('Core\ManagedLibraries\NAudio.Core.dll')" />
    <EmbeddedResource Include="Core\ManagedLibraries\NAudio.WinMM.dll" LogicalName="naudio.winmm.dll" Condition="Exists('Core\ManagedLibraries\NAudio.WinMM.dll')" />
    <EmbeddedResource Include="Core\ManagedLibraries\Newtonsoft.Json.dll" LogicalName="newtonsoft.json.dll" Condition="Exists('Core\ManagedLibraries\Newtonsoft.Json.dll')" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="hey_pie_com.quant.onnx" LogicalName="oww.model.hey_pie_com.quant.onnx" Condition="Exists('hey_pie_com.quant.onnx')" />
    <EmbeddedResource Include="$(PkgMicrosoft_ML_OnnxRuntime)\runtimes\win-x86\native\onnxruntime.dll" LogicalName="onnxruntime.native.win-x86.dll" />
    <EmbeddedResource Include="Core\NativeLibraries\onnxruntime-win-x64.dll" LogicalName="onnxruntime.native.win-x64.dll" Condition="Exists('Core\NativeLibraries\onnxruntime-win-x64.dll')" />
    <EmbeddedResource Include="Core\NativeLibraries\onnxruntime-linux-x64.so" LogicalName="onnxruntime.native.linux-x64.so" Condition="Exists('Core\NativeLibraries\onnxruntime-linux-x64.so')" />
    <EmbeddedResource Include="Core\NativeLibraries\onnxruntime-linux-arm64.so" LogicalName="onnxruntime.native.linux-arm64.so" Condition="Exists('Core\NativeLibraries\onnxruntime-linux-arm64.so')" />
    <EmbeddedResource Include="Core\NativeLibraries\onnxruntime-osx-x64.dylib" LogicalName="onnxruntime.native.osx-x64.dylib" Condition="Exists('Core\NativeLibraries\onnxruntime-osx-x64.dylib')" />
    <EmbeddedResource Include="Core\NativeLibraries\onnxruntime-osx-arm64.dylib" LogicalName="onnxruntime.native.osx-arm64.dylib" Condition="Exists('Core\NativeLibraries\onnxruntime-osx-arm64.dylib')" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CrossPlatformPatcher.Tests\**\*.cs" />
    <EmbeddedResource Remove="CrossPlatformPatcher.Tests\**\*" />
    <None Remove="CrossPlatformPatcher.Tests\**\*" />
    <Compile Remove="PAIcom.OWW\**\*.cs" />
    <Compile Include="PAIcom.OWW\AudioLockManager.cs" />
    <Compile Include="PAIcom.OWW\OpenWakeWordFeaturePipeline.cs" />
    <Compile Include="PAIcom.OWW\OpenWakeWordInferenceWorker.cs" />
    <Compile Include="PAIcom.OWW\OpenWakeWordSettings.cs" />
    <Compile Include="PAIcom.OWW\OpenWakeWordSettingsBuilder.cs" />
    <EmbeddedResource Remove="PAIcom.OWW\**\*" />
    <None Remove="PAIcom.OWW\**\*" />
  </ItemGroup>

</Project>
