<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../CrossPlatformPatcher.csproj" />
  </ItemGroup>

</Project>
