<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.17.3" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/melspectrogram.onnx" LogicalName="oww.feature.melspectrogram.onnx" Condition="Exists('Resources/melspectrogram.onnx')" />
    <EmbeddedResource Include="Resources/embedding_model.onnx" LogicalName="oww.feature.embedding.onnx" Condition="Exists('Resources/embedding_model.onnx')" />
  </ItemGroup>

</Project>
